steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.base'
      - '-t'
      - 'gcr.io/research-intel-agents/base:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/research-intel-agents/base:latest'
timeout: 1200s
