steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'src/jobs/arxiv_watcher/Dockerfile'
      - '-t'
      - 'gcr.io/research-intel-agents/arxiv-watcher:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/research-intel-agents/arxiv-watcher:latest'
timeout: 600s
